# Generated by Django 2.2.8 on 2020-04-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_column='Phone Number', max_length=13, null=True, unique=True),
        ),
    ]
