# Generated by Django 2.2.8 on 2020-04-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_auto_20200420_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_column='Is Active', default=True, help_text='Designates whether this user should be considered active or not.', verbose_name='is_active'),
        ),
    ]
